#sample pipeline for kubernetes ci/cd
pipeline:
  
  verify-env:
    image: docker
    commands:
     - "echo host: ${DOCKER_HOST}"
     - "hostname"
     - "export"
#     - "docker version"
  
#  build:
#    image: openjdk:8-slim
#    environment:
#      VERSION: "${DRONE_TAG}"
#      COMMIT: "${DRONE_COMMIT_SHA:0:7}"
#    commands:
#      - "MAVEN_OPTS='-Xmx200m' ./mvnw clean install"

  fake-build:
      image: alpine
      commands:
       - "mkdir -p target/"
       - "touch target/spring-boot-rest-sample-1.0.0.jar"

  publish:
    image: plugins/docker
    repo: registry/springapp
    registry: registry.kube-system
    insecure: true
    debug: true
    launch_debug: true
