version: '3.7'
services:
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sample
        volumes:
            - mysql-data:/var/lib/mysql
    spring-boot:
        build: .
        environment:
            - SPRING_PROFILES_ACTIVE=docker
        volumes:
          - /dev/urandom:/dev/random
        ports:
            - "8080:8080"
volumes:
    mysql-data:
