version: '2'
services:
    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=sample
        volumes:
            - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
